# Welcome to Jekyll!
title: The QRL Contributors
email: jack@theqrlcontributors.org
description: >- # this means to ignore newlines until "baseurl:"
  Contribution is the backbone of any opensource project like The QRL, and is emergent 
  from the community that surrounds it. It's important to keep things not only accessible 
  and open, but also simple, enticing, guided, cohesive, and malleable to the changing needs 
  of both the project and how it fits into the wider cryptocurrency and global space.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://theqrlcontributors.org" # the base hostname & protocol for your site, e.g. http://example.com
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
include: ["_pages"]
logo: "/assets/logo/logorefresh.svg"
masthead_title: "The QRL Contributors"
repository: "theqrl-community/theqrlcontributors.org"
# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.19.3"
minimal_mistakes_skin: "air"
plugins:
  - jekyll-feed
  - jekyll-include-cache
